### PR TITLE
Fixed timecode calculation for some edge cases and allow more than 99 hours

### PR DESCRIPTION
**Pull request by phigrofi**
* The previous calculation failed with certain input values: See test cases
* For large projects we need more than 99 hours. I increased the maximum hours to 999

### CODE REVIEW

**Comment by julik** [comment]
Looks nice!

A few questions though:
* There are hard build failures on older Rubies (probably BigDecimal-related). I know you won't like this but I would not want to necessarily make the gem 1.8.7-incompatible, because for many end users upgrading their shitty OS is impossible (such is post).
* The gemspec is rebuilt from Gemfile when a build is done by Jeweler, again: some people don't like it/find it unnecessary but I use it for over 20 gems at this point (Gemfile producing a gemspec on build) and switching to something else is extra work that I rather not do. What happens to the dependencies when you run `bundle exec rake gemspec`?
* With the 999 hours limit - it can in theory be anything, but I primarily worked with situations where printing such an hour count would just roll over. Could you maybe tell me what the use case is for this?
* Is a BigDecimal really needed for the framerate? or are you using it for the sake of just having proper decimals everywhere when computing the TC from `frames/fps`? I would imagine that for situations where the framerate is an int you could just keep on using a Fixnum and that would also use int arithmetic, which is supposed to be faster.

**Comment by phigrofi** [comment]
* We tried to fix the calculation problem with BigDecimals first and then rewrote the #validate! method. But now after rewriting, BigDecimals are not necessary any more (Good point). Travis is happy now.
* Ok I switched back to the previous gemspec and Gemfile
* We have large dailies projects where we want to show the total duration in timecode format. Here 99 hours is not enough. It would be a really helpful feature.
* See first bullet

**Comment by phigrofi** [comment]
Thanks for the merge!

**Comment by julik** [comment]
My pleasure. Looking at it now in a notch more detail - will you be ok if I add a method like `to_s_without_rollover` to get the number of hours printed completely? Then I can remove the hour cap but `to_s` will still return something that is usable in EDLs.

Otherwise the `to_s` method can now return stuff most oldschool tools will refuse to consume

**Comment by phigrofi** [comment]
Sounds great!

**Pull request merged**
